"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var users_ts_1 = require("../controllers/users.ts");
var router = express_1.default.Router();
router.post("/", users_ts_1.createUser);
router.get("/:id", users_ts_1.getUserById);
router.delete("/:id", users_ts_1.deleteUser);
router.patch("/:id", users_ts_1.updateUser);
exports.default = router;
